### PR TITLE
Fix tail origin for negative stealth values

### PR DESCRIPTION
**Pull request by SillyFreak**
The `stealth` mark is pretty versatile: for `stealth: 0.5`, the mark looks "normal", with `stealth: 0` it is basically the same as `solid`, and `stealth: -1` results in a diamond.

However, the `tail-origin` is fixed to the position where the triangular hull for `stealth >= 0` would end, so for bent edges, the bigger length of a mark with `stealth < 0` is not considered for its rotation on the arc -- see e.g. [this new test case](https://github.com/Jollywatt/typst-fletcher/blob/4dec0c2bb84f14e638deaddf9bd53d99d1cfb69c/tests/mark-stealth/ref/5.png).

This PR will fix the `tail-origin` calculation. Optionally, this more flexible stealth mark could be used as the basis for `diamond`. The current rotated square approach can't handle cap offsets well, since the rotation is not considered in the calculation; the difference can be seen [here](https://github.com/Jollywatt/typst-fletcher/pull/57/commits/45bf8361c2d6a4fd7b70d823e4cedd6b58f34924#diff-e296bc3be53bf3af57452b6907eabfa480593ce0d104281fccc8eb43df5c8b53). Another advantage would be that this would allow diamonds that are not square but a rhombus.

### CODE REVIEW

**Comment by Jollywatt** [comment]
this looks great! But I think this one is slightly wrong:



The tail origin is floating too far left.
Maybe this is just a matter of changing the `< 0` to `<= 0` or something?

**Comment by SillyFreak** [comment]
I noticed; this is actually the current behavior: [old](https://github.com/Jollywatt/typst-fletcher/pull/57/commits/0462e9c2b8cb4430dc1a394b5fc5254e5c12533d#diff-1513ac889775337c3ca3ed168784f5f4219b6569f4dc6c037eb5edd7985b458fL106), [new](https://github.com/Jollywatt/typst-fletcher/pull/57/commits/0462e9c2b8cb4430dc1a394b5fc5254e5c12533d#diff-1513ac889775337c3ca3ed168784f5f4219b6569f4dc6c037eb5edd7985b458fR117-R121). I plan to fix it, but wanted to get a draft out before I had to leave :)

What do you think about the overshoot [here](https://github.com/Jollywatt/typst-fletcher/pull/57/commits/4dec0c2bb84f14e638deaddf9bd53d99d1cfb69c#diff-38798a2d4834e11eb51de01177d16cd6be92119fec62080af8356a7128124051)? Do you consider that a bug, or a feature akin to microtype shifting punctuation beyond a margin?

**Comment by SillyFreak** [comment]
I tried yesterday to preview the manual to see if there's anything that should be changed there, but after [managing to do it](https://forum.typst.app/t/is-an-assert-supposed-to-be-able-to-change-behavior-when-it-doesnt-fail/1433?u=sillyfreak) it didn't seem so, so I think this is ready.

Again, there's a technically separate change in here to use the stealth head for the diamond mark:

> Optionally, this more flexible stealth mark could be used as the basis for diamond. The current rotated square approach can't handle cap offsets well, since the rotation is not considered in the calculation; the difference can be seen [here](https://github.com/Jollywatt/typst-fletcher/pull/57/commits/45bf8361c2d6a4fd7b70d823e4cedd6b58f34924#diff-e296bc3be53bf3af57452b6907eabfa480593ce0d104281fccc8eb43df5c8b53). Another advantage would be that this would allow diamonds that are not square but a rhombus.

If you don't agree with that change, I can remove it from the branch.

**Comment by Jollywatt** [comment]
This looks good, thanks. I've simplified the math a bit for finding the miter correction, but will commit that after accepting this PR. (Is it possible for me to add commits here?)

**Comment by Jollywatt** [comment]
(See a011539846850ad466f16fde715ab6f83a6512f4)

**Pull request merged**
